services:
  web:
    build: .
    expose:
      - "8003"
    env_file:
      - .env
    volumes:
      - motomeet_static:/app/staticfiles
      - motomeet_media:/app/media
    restart: always
    networks:
      - shared
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  motomeet_static:
    external: true
  motomeet_media:
    external: true

networks:
  shared:
    external: true
    name: shared_network