# Generated by Django 6.0.2 on 2026-02-22 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='meetup',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meetups_attending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meetups/'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(default='temp-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
