# Generated by Django 6.0.2 on 2026-02-23 16:02

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0002_alter_meetup_options_rename_name_meetup_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['-date'], 'verbose_name': 'Meet-up', 'verbose_name_plural': 'Meet-ups'},
        ),
        migrations.AddField(
            model_name='meetup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meetup',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meetups_attending', to=settings.AUTH_USER_MODEL, verbose_name='Deelnemers'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateTimeField(verbose_name='Datum & tijd'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Beschrijving'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meetups/', verbose_name='Afbeelding'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titel'),
        ),
    ]
