# Generated by Django 6.0.2 on 2026-02-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_alter_meetup_options_meetup_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Eind datum & tijd'),
        ),
    ]
