# Generated by Django 6.0.2 on 2026-02-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_meetup_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetup',
            options={'ordering': ['-start_date'], 'verbose_name': 'Meet-up', 'verbose_name_plural': 'Meet-ups'},
        ),
        migrations.RenameField(
            model_name='meetup',
            old_name='date',
            new_name='start_date',
        ),
    ]
