# Generated by Django 6.0.2 on 2026-02-24 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_alter_meetup_options_rename_date_meetup_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='document_link',
            field=models.URLField(blank=True, null=True, verbose_name='Document link'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='route_link',
            field=models.URLField(blank=True, null=True, verbose_name='Route link'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Reactie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetup_comments', to=settings.AUTH_USER_MODEL)),
                ('meetup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meetups.meetup')),
            ],
            options={
                'verbose_name': 'Reactie',
                'verbose_name_plural': 'Reacties',
                'ordering': ['created_at'],
            },
        ),
    ]
