# Generated by Django 6.0.2 on 2026-02-25 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_meetup_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='invited_friends',
            field=models.ManyToManyField(blank=True, help_text='Vrienden uitgenodigd voor deze private meetup', related_name='invited_to_meetups', to=settings.AUTH_USER_MODEL, verbose_name='Uitgenodigde vrienden'),
        ),
        migrations.AddField(
            model_name='meetup',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Publieke meetups zijn zichtbaar voor iedereen. Private meetups zijn alleen voor uitgenodigde vrienden.', verbose_name='Publieke meetup'),
        ),
    ]
