# Generated by Django 6.0.2 on 2026-02-28 12:35

import meetups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_meetup_invited_friends_meetup_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meetups/', validators=[meetups.models.validate_image_size], verbose_name='Afbeelding (bijv. screenshot van de route)'),
        ),
    ]
