# Generated by Django 6.0.2 on 2026-02-22 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geboortedatum', models.DateField(verbose_name='Geboortedatum')),
                ('woonplaats', models.CharField(max_length=100, verbose_name='Woonplaats')),
                ('motor_model', models.CharField(max_length=100, verbose_name='Motor Model')),
                ('gebruikersnaam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
