# Generated by Django 6.0.2 on 2026-02-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiel',
            name='geboortedatum',
            field=models.DateField(blank=True, null=True, verbose_name='Geboortedatum'),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='motor_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Motor Model'),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='woonplaats',
            field=models.CharField(blank=True, max_length=100, verbose_name='Woonplaats'),
        ),
    ]
