# Generated by Django 6.0.2 on 2026-02-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profiel_geboortedatum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='route_1',
            field=models.URLField(blank=True, null=True, verbose_name='Route 1'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='route_2',
            field=models.URLField(blank=True, null=True, verbose_name='Route 2'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='route_3',
            field=models.URLField(blank=True, null=True, verbose_name='Route 3'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='route_4',
            field=models.URLField(blank=True, null=True, verbose_name='Route 4'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='route_5',
            field=models.URLField(blank=True, null=True, verbose_name='Route 5'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube'),
        ),
    ]
