# Generated by Django 6.0.2 on 2026-02-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profiel_facebook_profiel_instagram_profiel_route_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='route_1_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Route 1 naam'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='route_2_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Route 2 naam'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='route_3_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Route 3 naam'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='route_4_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Route 4 naam'),
        ),
        migrations.AddField(
            model_name='profiel',
            name='route_5_naam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Route 5 naam'),
        ),
    ]
