# Generated by Django 6.0.2 on 2026-02-25 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profiel_route_1_naam_profiel_route_2_naam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='vrienden',
            field=models.ManyToManyField(blank=True, related_name='toegevoegd_door', to=settings.AUTH_USER_MODEL),
        ),
    ]
