# Generated by Django 6.0.2 on 2026-02-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profiel_vrienden'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='profiel_foto',
            field=models.ImageField(blank=True, null=True, upload_to='profielen/', verbose_name='Profielfoto'),
        ),
    ]
