# Generated by Django 6.0.2 on 2026-02-28 12:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profiel_profiel_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiel',
            name='profiel_foto',
            field=models.ImageField(blank=True, null=True, upload_to='profielen/', validators=[accounts.models.validate_image_size], verbose_name='Profielfoto'),
        ),
    ]
